name: foundit_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.14.2 # 👈 WORKING VERSION
  cloud_firestore: ^5.6.6
  mailer: ^6.0.0
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  uuid: ^4.5.1
  stream_chat_flutter: ^8.0.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_core: ^0.0.9
  provider: ^6.1.5
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
