name: foundit_app
description: "A new Flutter project."
publish_to: 'none' # This is so the package won't be published to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase Integration
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  # 🧠 State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.5

  # 💬 Chat Features
  stream_chat_flutter: ^8.0.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_core: ^0.0.6
  flutter_chat_types: ^3.6.2

  # 📷 Media & File Handling
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  open_file: ^3.2.1
  chewie: ^1.8.1

  # 🧰 Utilities
  mailer: ^6.0.0
  uuid: ^4.5.1
  collection: ^1.18.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  url_launcher: ^6.2.6
  meta: ^1.12.0

  # ✨ UI & Animation
  flutter_animate: ^4.2.0
  emoji_picker_flutter: ^1.6.2
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/MIULogo.png
